//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiddlerSanitizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiddlerSanitizer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Sanitizer.
        /// </summary>
        internal static string AuthSanitizerTabName {
            get {
                return ResourceManager.GetString("AuthSanitizerTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redacted Text:.
        /// </summary>
        internal static string RedactedText {
            get {
                return ResourceManager.GetString("RedactedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request headers.
        /// </summary>
        internal static string RequestHeaders {
            get {
                return ResourceManager.GetString("RequestHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response headers.
        /// </summary>
        internal static string ResponseHeaders {
            get {
                return ResourceManager.GetString("ResponseHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanitize after each session (request/response).
        /// </summary>
        internal static string SanitizeAfterEachSession {
            get {
                return ResourceManager.GetString("SanitizeAfterEachSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanitize during save.
        /// </summary>
        internal static string SanitizeDuringSave {
            get {
                return ResourceManager.GetString("SanitizeDuringSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanitize Headers.
        /// </summary>
        internal static string SanitizeHeaders {
            get {
                return ResourceManager.GetString("SanitizeHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing.
        /// </summary>
        internal static string Timing {
            get {
                return ResourceManager.GetString("Timing", resourceCulture);
            }
        }
    }
}
